nmHoistingLimits: workspaces

nodeLinker: pnp

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
  jest-config@*:
    dependencies:
      ts-node: "*"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
